### PR TITLE
Implementation of a plugin versioning system.

### PR DESCRIPTION
**Pull request by alpapad**
A @Version annotation can be used at the Plugin or each plugin method
level, which will be used to determine if a patch should be applied to
the class being loaded. Note, versions are only applicable to patching
and not to runtime redefinitions (it would be extremly costly)

There is a single entry point

				if(pluginAnnotation.shouldCheckVersion()) {
					DeploymentInfo info = DeploymentInfo.fromClassLoader(loader);
					if(!pluginAnnotation.matches(info)) {
						LOGGER.debug("SKIPPING METHOD: {}, Deployment info: {}\n did not match with {}\n or {}", pluginAnnotation.method, info, pluginAnnotation.methodMatcher, pluginAnnotation.pluginMatcher);
						return classfileBuffer;
					}
				}

in class org.hotswap.agent.annotation.handler.OnClassLoadedHandler. Maybe, it makes sense to have a global switch and disable the feature altogether.

The El plugins (including the plugin for jboss el 3.0) and hibernate 3/4 plugins have been annotated.

For hibernate there is a missing version annotation for the validators. Not sure which version should go where (wildfly with hibernate 3 in war requires hib-validation 5 {the original wfly module with CDI patches!!} else it will not start!)

The whole thing has been tested in wildfly10. I believe this should be one of the hardest platforms due to vfs. We need to test tomcat and jetty.....

### CODE REVIEW

**Comment by edudant** [comment]
Wow, the idea with maven/manifest is great.

Let me do some tests during the weekend on our projects, at least on jetty. Have you tried running tests on HotswapAgentExamples?

Pull request does not contain TEST.MF and other test resources, hence the test fails.Please commit those files.

Usage of Spring utils is ok and I understand the licence in those files. Is there any reason you use Apache 2 licence for your files? I am no expert on licences, I used GPL just to force the project to remain public.

PurgeWildFlyBeanELResolverCacheCommand,equals() - should probably contain className, otherwise two refresh commands with the same classloader and different method within timeout will be merged into one call (of the first className).

**Comment by skybber** [comment]
As far as Apache licence - it is compatible with GPL licence. Apache licence  can use in GPL code, noot the other way around.
reegards Vladimir

**Comment by alpapad** [comment]
About the license, you want it change to gpl? Is there a template to use?

**Comment by alpapad** [comment]
Something like this?

Copyright 200X My Name

This file is part of Foobar.

Foobar is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Foobar is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Foobar. If not, see http://www.gnu.org/licenses/.


http://stackoverflow.com/questions/153148/adding-the-gpl-license-to-c-sharp-projects

**Comment by skybber** [comment]
I dont think we can change existing Apache licence to GPL. But according http://www.apache.org/licenses/GPL-compatibility.html we can use Apache licenced code in project with GPL licence.

**Comment by alpapad** [comment]
Not a problem with GPL, just send me a sample header licence and I will
change.. From what I am reading, a licence should exist in every file.

To be honest.... i completely missed the big license file in the root of
the project, and just copied the Spring one :-(

**Comment by alpapad** [comment]
HI all,

I have updated the license

**Comment by skybber** [comment]
Merged. Thank you! I'm sorry for delay.

**Comment by alpapad** [comment]
NP. Please have a look @ the windows patch, as it does make a difference
for windows users.

:-)

**Pull request closed without merging**
