### PR TITLE
Log4j2 plugin

### PR DESCRIPTION
**Pull request by sycyhy**
* Add Log4j2 automatic reconfiguration plugin

### CODE REVIEW

**Comment by skybber** [comment]
It look very nice! Could you please fix compatibility problems for versions <2.3 where LoggerContext.reconfigure(URI) method is missing ? You can put the plugin initialization hooks into LoggerContext.reconfigure() method in that case. Thanks! [http://grepcode.com/file/repo1.maven.org/maven2/org.apache.logging.log4j/log4j-core/2.2/org/apache/logging/log4j/core/LoggerContext.java#LoggerContext](LoggerContext v2.2)

**Comment by sycyhy** [comment]
@skybber 
Thanks. I added support for version < 2.3. I needed to hook to another method but it seems everything is working smootly now :). 

This is my first pull request on any open-source project ever so I'm not sure - should I also update main README.md to point that it supports Log4j2 now ?:)

**Comment by skybber** [comment]
Nice piece of code! Please add :
- The basic information about the plugin to README , 
- If you want, put your name to HA's authors section
Thank you.

**Comment by skybber** [comment]
Plus please add some info message in init method:

            LOGGER.info("Log4j2 plugin initialized.");

**Comment by sycyhy** [comment]
Done !:)

Hopefully you can merge now :)

**Pull request merged**
