### PR TITLE
Resteasy registry plugin

### PR DESCRIPTION
**Pull request by alpapad**
Resteasy registry plugin

### CODE REVIEW

**Comment by alpapad** [comment]
NOTE: Plugin NOT added in the aggregator...

**Comment by skybber** [comment]
Thanks!

**Comment by alpapad** [comment]
Not merged?

**Comment by skybber** [comment]
Thanks, I've had a travis error there but it was ok.

**Comment by alpapad** [comment]
Travis builds were triggered from my master branch and since there is no
travis config in the PR it tries to build with.... rake!!!.

I disabled it, you should not see any errors now.

We could use travis for simple checks (just the compile).
I created an issue for the travis team, it seems it is possible to have
openjdk with dcevm in travis but they first have to white-list it.

Waiting for their response......

**Pull request merged**
