### PR TITLE
Support disable plugins by vm option -DdisablePlugin=xxxxx

### PR DESCRIPTION
**Pull request by gejun123456**
make user easyier to use for disable some plugins.

### CODE REVIEW

**Comment by skybber** [comment]
Could you please add to README.md how to use this option? There is a section about `disablePlugin` for agent, so you can extend or modify it.

**Comment by gejun123456** [comment]
updated, thanks

**Comment by skybber** [comment]
The mechanism is good. I rethink it again and suggest renaming the parameter because it will become a global parameter and the name `disablePlugin` is too generic. I suggest `-Dhotswapagent.disablePlugin`

**Comment by gejun123456** [comment]
yes, it would be better. updated

**Comment by skybber** [comment]
Great, thank you for contribution!

**Pull request merged**
