### PR TITLE
New Feature Added to MyBatis Plugin: Annotation SQL Reload Functionality

### PR DESCRIPTION
**Pull request by homejim**
1.Feature Added: Enable SQL reload when using annotation-based SQL.
2.Feature Added: Enable reload when there are changes in entity classes, such as result entity or parameter entity classes.
3.Refactor MyBatisTransformers code to improve readability and maintainability.

### CODE REVIEW

**Comment by homejim** [comment]
@skybber 
In the previous version of the MyBatis plugin, reload was only triggered when changes were made to XML files. However, MyBatis also supports annotation-based SQL, and in such cases, MyBatis does not update when classes are modified. My commit introduces a reload feature for annotation-based SQL. 

I will also submit related unit tests in the future, including tests for previous fixes made to spring-mybatis.

**Comment by skybber** [comment]
@homejim great work! Would it be possible to add junit tests for it? You can look at OwbJakartaPluginTest / swapClasses() method how to redefine class in junit test.

**Comment by homejim** [comment]
> @homejim great work! Would it be possible to add junit tests for it? You can look at OwbJakartaPluginTest / swapClasses() method how to redefine class in junit test.

Yes, I will add the unit tests for these features in the next few days

**Comment by skybber** [comment]
Thanks!

**Pull request merged**
