### PR TITLE
the maven dependency scope of MyBatis should be "provided"

### PR DESCRIPTION
**Pull request by StarJourneyMingsing**

### CODE REVIEW

**Comment by skybber** [comment]
If you don't use `provided`, will it cause any issues for you? HA doesn't usually declare external dependencies as `provided` because it’s an agent. What is your use case?

**Comment by StarJourneyMingsing** [comment]
We  have a hotswap-agent-internal.jar, which introduces the community's org.hotswapagent. We will first package it using the Maven assembly plugin, then use the Maven shade plugin to rename dependencies. So if any dependency in HotswapAgent has a scope other than provided, it will be included in the final jar file (such as the MyBatis related libraries). In fact, it may not be necessary to set the dependency scope to provided. We have found that we can also use the <includes> tag in the Maven shade plugin to include the dependencies we need in the jar file.

**Comment by StarJourneyMingsing** [comment]
We  have an internal HotswapAgent, which introduces the community's HotswapAgent and has a further development. We first use the Maven Assembly plugin for packaging and then use the Maven Shade plugin to rename JSON dependencies (to prevent conflicts between the included JSON dependencies and the application's JSON dependencies). 

        Therefore, if a dependency in HotswapAgent does not have a scope of 'provided', it will be included in the final jar file (for example, MyBatis related libraries). However, it indeed seems unnecessary to declare external dependencies as 'provided'. We have found that we can also use the <includes> tag in the Maven shade plugin to include the dependencies we need in the jar file.

        So, this PR can be closed. However, I still don't quite understand why external dependencies like MyBatis doesn't have its scope set to 'provided', because MyBatis should be undoubtedly provided by the application (although hotswap-agent.jar only included org.hotswapagent:* in the final jar file using the Maven Assembly plugin).

**Comment by skybber** [comment]
May be `test` is better scope in this case, since a lot of plugins have junit tests.

**Comment by StarJourneyMingsing** [comment]
> May be `test` is better scope in this case, since a lot of plugins have junit tests.

But the dependency which has "provided" scope is also available on the test classpath, isn't it?

> provided - this is much like compile, but indicates you expect the JDK or a container to provide it at runtime. It is only available on the compilation and test classpath, and is not transitive.

from: https://maven.apache.org/pom.html

**Pull request merged**
