### PR TITLE
Fix enum field update

### PR DESCRIPTION
**Pull request by liuzhengyang**
image

The name of the static field in Enum class is "$VALUES" instead of "ENUM$VALUES".

By the way, i can't run tests ClassInitTest, it throws exception `throw new IllegalStateException("Plugin manager is not correctly initialized `, maybe because of junit running order or other issue.
But i have tested this change by some tricky methods.

### CODE REVIEW

**Comment by liuzhengyang** [comment]
> What java version / compiler are you using?

Java8 and Java11

**Comment by skybber** [comment]
It looks that there is no standard for the name of enum field. I've checked output of different java compilers using `javap -p EnCommonRequestStatus.class` and Eclipse JDT uses `ENUM$VALUES;` , javac uses `$VALUES;`. Better solution should check both versions. Could you please modify PR?

**Comment by liuzhengyang** [comment]
I have modified PR. 
First check field type is array, then check field name start with `$VALUES` or `ENUM$VALUES`.
Because when that name clash with enum field name, javac append `$` `$$` and eclipse compiler append `_0` `_1`

**Comment by skybber** [comment]
Looks great, thanks!

**Pull request merged**
