### PR TITLE
resolve bean definition with start-up classloaer

### PR DESCRIPTION
**Pull request by smallfour**
when refresh class, resolve bean definition with start-up classloaer.

### CODE REVIEW

**Comment by smallfour** [comment]
This change will set start-up ClassLoader as default ClassLoader when to do refreshClass. If don't do this, ClassPathBeanDefinitionScannerAgent maybe can't resolve Annotation, Because they use different ClassLoader at startup and to do refreshClass.

**Comment by skybber** [comment]
It is correct to setup contextClassLoader before framework calls. There is common mechanism in the HA how to get `appClassLoader`. AppClassLoader it is stored in plugin class, in case of Spring it is in `SpringPlugin.appClassLoader`. Then it is passed to `XyzCommand`, in our case `ClassPathBeanRefreshCommand` and then it could be passed to `refreshClass` call, but in case of SpringPluging it is missing there. Could you please modify your code and pass appClassLoader from ClassPathBeanRefreshCommand to `ClassPathBeanDefinitionScannerAgent.refreshClass` ?

**Comment by smallfour** [comment]
@skybber   I have modified my code, pass appClassLoader from ClassPathBeanRefreshCommand as ClassPathBeanDefinitionScannerAgent.refreshClass argument. please check it!

**Comment by skybber** [comment]
Great, thanks for contribution.

**Pull request merged**
