### PR TITLE
Vaadin 14 compatibility

### PR DESCRIPTION
**Pull request by joheriks**
Update the plugin to reflect changes in Vaadin 14 and 15.

### CODE REVIEW

**Comment by skybber** [comment]
Thanks!

**Comment by pleku** [comment]
Hi @skybber when could we expect this into a release ? Or even a snapshot ?

Just interested in the timeline that when could we get this to users.

**Comment by skybber** [comment]
Hi, done now as 1.4.1-SNAPSHOT

**Comment by pleku** [comment]
Awesome, thousand thanks @skybber !

**Pull request merged**
