### PR TITLE
Add Intellij HotSwapHelper plugin.

### PR DESCRIPTION
**Pull request by gejun123456**
Add Intellij HotSwapHelper plugin in IDE part.

### CODE REVIEW

**Comment by skybber** [comment]
Thanks!

**Comment by homejim** [comment]
@gejun123456 
I tried using this plugin and read through some of the code. I think it’s still somewhat difficult for a new user to use, and there is room for improvement. My understanding is:

1. Automatically add parameters like -XX:HotswapAgent=fatjar and -XX:+AllowEnhancedClassRedefinition on top of the original configuration.
2. Specify the hotswap-agent.jar with output results added.

The user still has to do quite a few things:

1. Understand DCEVM on their own, and download and install the JDK.
2. Specify the JDK at runtime.
3. It seems like the hotswap-agent.jar cannot be specified manually? What if I want to upgrade it? Do I need to manually overwrite C:/tmp/HotSwapAgent/?

Maybe you could optimize these aspects.

**Comment by skybber** [comment]
@gejun123456 @homejim I recommend using `-XX:HotswapAgent=external`. This option `--add-opens` all JDK modules that HotswapAgent requires to be opened. Additionally, use the standard Java agent argument `-javaagent:<path_to_latest_ha>/hotswap-agent.jar`. If an external agent is used, the user (or HotswapHelper plugin) can place HotswapAgent anywhere where has access and is not restricted by the OS access rules, as if JBR is placed in a system directory like `/usr/lib/jvm/jbr21/`.

**Comment by gejun123456** [comment]
@homejim @skybber Thanks for the suggestion, the plugin will support user configure agent manually in later versions. 
For downloading jdk, i think it's easyier for user to use, or user has to manully search the jdk and install DCEVM.

**Comment by gejun123456** [comment]
image 
Manually set jar file is supported, thanks. will add more feature in later versions.
[HotSwapHelper-1.0.2.zip](https://github.com/user-attachments/files/16739002/HotSwapHelper-1.0.2.zip)

**Pull request merged**
