### PR TITLE
fix: UnmodifiedMap has some transient fields which cause problems

### PR DESCRIPTION
**Pull request by cvictory**
fix: UnmodifiedMap has some transient fields which cause problems

In org.springframework.boot.env.PropertiesPropertySourceLoader ：
```
public List<PropertySource<?>> load(String name, Resource resource) throws IOException {
		List<Map<String, ?>> properties = loadProperties(resource);
		if (properties.isEmpty()) {
			return Collections.emptyList();
		}
		List<PropertySource<?>> propertySources = new ArrayList<>(properties.size());
		for (int i = 0; i < properties.size(); i++) {
			String documentNumber = (properties.size() != 1) ? " (document #" + i + ")" : "";
			propertySources.add(new OriginTrackedMapPropertySource(name + documentNumber,
					Collections.unmodifiableMap(properties.get(i)), true));
		}
		return propertySources;
	}
```

If we use Collections.unmodifiableMap to create the map, it will cause the map cannot be modified specially use the keySet or entrySet method.

```
// java.util.Collections.UnmodifiableMap 

        private transient Set<K> keySet;
        private transient Set<Map.Entry<K,V>> entrySet;
        private transient Collection<V> values;
....
       public Set<K> keySet() {
            if (keySet==null)
                keySet = unmodifiableSet(m.keySet());
            return keySet;
        }

        public Set<Map.Entry<K,V>> entrySet() {
            if (entrySet==null)
                entrySet = new UnmodifiableEntrySet<>(m.entrySet());
            return entrySet;
        }

```

### CODE REVIEW

**Comment by cvictory** [comment]
@skybber please review this pr when you're free.

**Comment by skybber** [comment]
variables are OK now, please fix methods also ($ha$loadList0 -> $$ha$loadList0), the purpose is to differentiate HA methods from rest of methods. Thanks!

**Comment by cvictory** [comment]
> variables are OK now, please fix methods also ($ha$loadList0 -> $$ha$loadList0), the purpose is to differentiate HA methods from rest of methods. Thanks!

done

**Comment by skybber** [comment]
Great, thanks!

**Pull request merged**
