### PR TITLE
feat(mybatis-plus): Add MyBatisPlus plugin to HA

### PR DESCRIPTION
**Pull request by homejim**
Add MyBatisPlus plugin to HA：support MybatisPlus versions  between 3.4.0 and 3.5.7

### CODE REVIEW

**Comment by homejim** [comment]
@skybber After careful consideration, I decided to create a separate plugin for MyBatis Plus. The main reasons are:

1. Easier maintenance without affecting the functionality of the original MyBatis plugin.
2. Simplified unit testing.
3. Independent version management for MyBatisPlus.

**Comment by skybber** [comment]
Great job!

**Comment by skybber** [comment]
You might consider adding your name to the list of HotswapAgent authors in the README.md file.

**Comment by homejim** [comment]
FIX [475](https://github.com/HotswapProjects/HotswapAgent/issues/475)

**Pull request merged**
