### PR TITLE
Add unit test code for the MyBatis plugin.

### PR DESCRIPTION
**Pull request by homejim**
1.Add unit tests for #558:: When using annotation-based SQL, verify the reload after the class has been modified.
2.Add MybatisSpringBootTest to verify reload behavior in Spring Boot applications
- Verify issue #557: Application can successfully reload without configuring mybatis.config-location.
- Verify issue #558: Application can successfully reload when annotated SQL classes change without configuring mybatis.config-location.

### CODE REVIEW

**Comment by homejim** [comment]
@skybber Added unit tests for the MyBatis plugin code that I previously submitted.

**Comment by skybber** [comment]
Great work , THANKS!!!

**Comment by skybber** [comment]
@homejim `testUserAnnotationSQL` is failing in `mvn clean package`, seems it is working from IDE.

**Comment by homejim** [comment]
> @homejim `testUserAnnotationSQL` is failing in `mvn clean package`, seems it is working from IDE.
@skybber 
I downloaded the latest HotswapAgent code, then commented out all other unit test code for MyBatis, keeping only MyBatisPluginAnnoTest and removing @Ignore. After compiling, I ran mvn test for the MyBatis plugin directly, and it worked fine. How can I reproduce the issue you mentioned?

image

**Comment by homejim** [comment]
> @homejim `testUserAnnotationSQL` is failing in `mvn clean package`, seems it is working from IDE.

image

I downloaded the latest HotswapAgent code, then commented out all other unit test code for MyBatis, keeping only MyBatisPluginAnnoTest and removing @Ignore. After compiling, I ran mvn test for the MyBatis plugin directly, and it worked fine. How can I reproduce the issue you mentioned?

**Comment by skybber** [comment]
I see next (mvn clean package):

```
Running org.hotswap.agent.plugin.mybatis.MyBatisPluginAnnoTest
HOTSWAP AGENT: 16:08:33.645 DEBUG (org.hotswap.agent.plugin.mybatis.MyBatisPlugin) - MyBatisPlugin - configuration file registered : /home/lada/workspaces/workspace-ha/HotswapAgent/plugin/hotswap-agent-mybatis-plugin/target/test-classes/org/hotswap/agent/plugin/mybatis/mybatis-config-anno.xml
HOTSWAP AGENT: 16:08:33.645 DEBUG (org.hotswap.agent.plugin.mybatis.proxy.ConfigurationProxy) - MyBatis runs in MyBatis-Spring mode, so there is no need to cache configuration-related data
2024-08-10 16:08:33.657 DEBUG 16648 --- [           main] o.a.i.transaction.jdbc.JdbcTransaction   : Opening JDBC Connection
2024-08-10 16:08:33.658 DEBUG 16648 --- [           main] o.a.i.transaction.jdbc.JdbcTransaction   : Setting autocommit to false on JDBC Connection [org.hsqldb.jdbc.JDBCConnection@2b0454d2]
2024-08-10 16:08:33.659 DEBUG 16648 --- [           main] o.a.i.transaction.jdbc.JdbcTransaction   : Resetting autocommit to true on JDBC Connection [org.hsqldb.jdbc.JDBCConnection@2b0454d2]
2024-08-10 16:08:33.659 DEBUG 16648 --- [           main] o.a.i.transaction.jdbc.JdbcTransaction   : Closing JDBC Connection [org.hsqldb.jdbc.JDBCConnection@2b0454d2]
HOTSWAP AGENT: 16:08:33.660 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [org.hotswap.agent.plugin.mybatis.testBeansHotswap.UserMapper] (autoHotswap)
2024-08-10 16:08:34.440  WARN 16648 --- [      Thread-26] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'mapper' and 'org.hotswap.agent.plugin.mybatis.Mapper' mapperInterface. Bean already defined with the same name!
2024-08-10 16:08:34.440  WARN 16648 --- [      Thread-26] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'bootUserMapper' and 'org.hotswap.agent.plugin.mybatis.springboot.BootUserMapper' mapperInterface. Bean already defined with the same name!
2024-08-10 16:08:34.441  WARN 16648 --- [      Thread-26] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'bootUserMapper2' and 'org.hotswap.agent.plugin.mybatis.springboot.BootUserMapper2' mapperInterface. Bean already defined with the same name!
2024-08-10 16:08:34.441  WARN 16648 --- [      Thread-26] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'userMapper' and 'org.hotswap.agent.plugin.mybatis.testBeansHotswap.UserMapper' mapperInterface. Bean already defined with the same name!
2024-08-10 16:08:34.441  WARN 16648 --- [      Thread-26] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'userMapper2' and 'org.hotswap.agent.plugin.mybatis.testBeansHotswap.UserMapper2' mapperInterface. Bean already defined with the same name!
2024-08-10 16:08:34.441  WARN 16648 --- [      Thread-26] o.m.s.mapper.ClassPathMapperScanner      : No MyBatis mapper was found in '[org.hotswap.agent.plugin.mybatis]' package. Please check your configuration.
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.268 sec <<< FAILURE! - in org.hotswap.agent.plugin.mybatis.MyBatisPluginAnnoTest
testUserAnnotationSQL(org.hotswap.agent.plugin.mybatis.MyBatisPluginAnnoTest)  Time elapsed: 1.251 sec  <<< FAILURE!
java.lang.AssertionError: null
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertTrue(Assert.java:53)
        at org.hotswap.agent.plugin.mybatis.MyBatisPluginAnnoTest.swapClasses(MyBatisPluginAnnoTest.java:98)
        at org.hotswap.agent.plugin.mybatis.MyBatisPluginAnnoTest.testUserAnnotationSQL(MyBatisPluginAnnoTest.java:84)

2024-08-10 16:08:34.913  INFO 16648 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2024-08-10 16:08:34.918  INFO 16648 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.

Results :

Failed tests: 
  MyBatisPluginAnnoTest.testUserAnnotationSQL:84->swapClasses:98 null
```

**Comment by skybber** [comment]
With `mvn clean package -X` :

```
HOTSWAP AGENT: 16:35:49.610 DEBUG (org.hotswap.agent.plugin.mybatis.MyBatisRefreshCommands) - Refreshing MyBatis configuration.
java.lang.IllegalStateException: Error invoking method org.mybatis.spring.SqlSessionFactoryBean.buildSqlSessionFactory([]) on org.mybatis.spring.SqlSessionFactoryBean@1cbc5693, params []
        at org.hotswap.agent.util.ReflectionHelper.invoke(ReflectionHelper.java:63)
        at org.hotswap.agent.util.ReflectionHelper.invoke(ReflectionHelper.java:120)
        at org.hotswap.agent.plugin.mybatis.proxy.SpringMybatisConfigurationProxy.refreshProxiedConfiguration(SpringMybatisConfigurationProxy.java:44)
        at org.hotswap.agent.plugin.mybatis.proxy.SpringMybatisConfigurationProxy.refreshProxiedConfigurations(SpringMybatisConfigurationProxy.java:36)
        at org.hotswap.agent.plugin.mybatis.MyBatisRefreshCommands.reloadConfiguration(MyBatisRefreshCommands.java:51)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.hotswap.agent.command.ReflectionCommand.doExecuteReflectionCommand(ReflectionCommand.java:207)
        at org.hotswap.agent.command.ReflectionCommand.executeCommand(ReflectionCommand.java:168)
        at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:43)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.hotswap.agent.util.ReflectionHelper.invoke(ReflectionHelper.java:58)
        ... 11 more
Caused by: org.springframework.core.NestedIOException: Failed to parse mapping resource: 'file [/home/lada/workspaces/workspace-ha/HotswapAgent/plugin/hotswap-agent-mybatis-plugin/target/test-classes/swapXML/BootUserMapper.xml]'; nested exception is java.io.FileNotFoundException: /home/lada/workspaces/workspace-ha/HotswapAgent/plugin/hotswap-agent-mybatis-plugin/target/test-classes/swapXML/BootUserMapper.xml
        at org.mybatis.spring.SqlSessionFactoryBean.buildSqlSessionFactory(SqlSessionFactoryBean.java:613)
        ... 16 more
Caused by: java.io.FileNotFoundException: /home/lada/workspaces/workspace-ha/HotswapAgent/plugin/hotswap-agent-mybatis-plugin/target/test-classes/swapXML/BootUserMapper.xml
        at org.springframework.core.io.FileSystemResource.getInputStream(FileSystemResource.java:192)
        at org.mybatis.spring.SqlSessionFactoryBean.buildSqlSessionFactory(SqlSessionFactoryBean.java:609)
        ... 16 more
```

seems that the file is missing in target:

```
lada@skybber ~/workspaces/workspace-ha/HotswapAgent $ ls /home/lada/workspaces/workspace-ha/HotswapAgent/plugin/hotswap-agent-mybatis-plugin/target/test-classes/swapXML/
BootUserMapper1.xml  BootUserMapper2.xml
```

**Comment by homejim** [comment]
According to the image, my system is Windows. I re-downloaded the latest code, commented out @Ignore, and tried running mvn clean package multiple times, but I did not encounter the mybatis plugin unit test failure.

image

**Comment by homejim** [comment]
> With `mvn clean package -X` :
> 
> ```
> HOTSWAP AGENT: 16:35:49.610 DEBUG (org.hotswap.agent.plugin.mybatis.MyBatisRefreshCommands) - Refreshing MyBatis configuration.
> java.lang.IllegalStateException: Error invoking method org.mybatis.spring.SqlSessionFactoryBean.buildSqlSessionFactory([]) on org.mybatis.spring.SqlSessionFactoryBean@1cbc5693, params []
>         at org.hotswap.agent.util.ReflectionHelper.invoke(ReflectionHelper.java:63)
>         at org.hotswap.agent.util.ReflectionHelper.invoke(ReflectionHelper.java:120)
>         at org.hotswap.agent.plugin.mybatis.proxy.SpringMybatisConfigurationProxy.refreshProxiedConfiguration(SpringMybatisConfigurationProxy.java:44)
>         at org.hotswap.agent.plugin.mybatis.proxy.SpringMybatisConfigurationProxy.refreshProxiedConfigurations(SpringMybatisConfigurationProxy.java:36)
>         at org.hotswap.agent.plugin.mybatis.MyBatisRefreshCommands.reloadConfiguration(MyBatisRefreshCommands.java:51)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>         at org.hotswap.agent.command.ReflectionCommand.doExecuteReflectionCommand(ReflectionCommand.java:207)
>         at org.hotswap.agent.command.ReflectionCommand.executeCommand(ReflectionCommand.java:168)
>         at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:43)
> Caused by: java.lang.reflect.InvocationTargetException
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>         at org.hotswap.agent.util.ReflectionHelper.invoke(ReflectionHelper.java:58)
>         ... 11 more
> Caused by: org.springframework.core.NestedIOException: Failed to parse mapping resource: 'file [/home/lada/workspaces/workspace-ha/HotswapAgent/plugin/hotswap-agent-mybatis-plugin/target/test-classes/swapXML/BootUserMapper.xml]'; nested exception is java.io.FileNotFoundException: /home/lada/workspaces/workspace-ha/HotswapAgent/plugin/hotswap-agent-mybatis-plugin/target/test-classes/swapXML/BootUserMapper.xml
>         at org.mybatis.spring.SqlSessionFactoryBean.buildSqlSessionFactory(SqlSessionFactoryBean.java:613)
>         ... 16 more
> Caused by: java.io.FileNotFoundException: /home/lada/workspaces/workspace-ha/HotswapAgent/plugin/hotswap-agent-mybatis-plugin/target/test-classes/swapXML/BootUserMapper.xml
>         at org.springframework.core.io.FileSystemResource.getInputStream(FileSystemResource.java:192)
>         at org.mybatis.spring.SqlSessionFactoryBean.buildSqlSessionFactory(SqlSessionFactoryBean.java:609)
>         ... 16 more
> ```
> 
> seems that the file is missing in target:
> 
> ```
> lada@skybber ~/workspaces/workspace-ha/HotswapAgent $ ls /home/lada/workspaces/workspace-ha/HotswapAgent/plugin/hotswap-agent-mybatis-plugin/target/test-classes/swapXML/
> BootUserMapper1.xml  BootUserMapper2.xml
> ```
It sounds like there might be a conflict between org.hotswap.agent.plugin.mybatis.MybatisSpringBootTest and org.hotswap.agent.plugin.mybatis.MybatisSpringTest. I'll work on resolving this issue as soon as possible

image

**Comment by homejim** [comment]
> According to the image, my system is Windows. I re-downloaded the latest code, commented out Ignore, and tried running mvn clean package multiple times, but I did not encounter the mybatis plugin unit test failure.
> 
> image

@skybber Did your Maven have any special configurations?

**Comment by skybber** [comment]
I cloned a fresh HA repository and ran `mvn clean package`, which completed without issues. `git diff` shows no differences on original repo, I'm puzzled about where the problem might be occurring. May be I'll start to use the new one.

**Comment by homejim** [comment]
> I cloned a fresh HA repository and ran `mvn clean package`, which completed without issues. `git diff` shows no differences on original repo, I'm puzzled about where the problem might be occurring. May be I'll start to use the new one.

Okay. I wrote a HA plugin for MyBatis Plus. Should my code be a standalone MyBatis Plus plugin, or should it be combined with the MyBatis plugin?@skybber 

https://github.com/baomidou/mybatis-plus

**Comment by skybber** [comment]
I'll leave it up to your decision. Generally:

- If the MyBatis-Plus plugin shares most of its code with the MyBatis plugin, it would be better to combine the plugins into one.
- The MyBatisPlus plugin can also use the MyBatis plugin as a dependency.
- If the MyBatisPlus plugin is not very extensive and there are no plans for significant future expansion, it’s fine to keep it as a separate plugin.
- Each additional new plugin slows down HA - fatjar, especially on architectures with a large number of classloaders, because all classes must be copied to all classloaders (unless delegation is used).

**Comment by homejim** [comment]
> I'll leave it up to your decision. Generally:
> 
> * If the MyBatis-Plus plugin shares most of its code with the MyBatis plugin, it would be better to combine the plugins into one.
> * The MyBatisPlus plugin can also use the MyBatis plugin as a dependency.
> * If the MyBatisPlus plugin is not very extensive and there are no plans for significant future expansion, it’s fine to keep it as a separate plugin.
> * Each additional new plugin slows down HA - fatjar, especially on architectures with a large number of classloaders, because all classes must be copied to all classloaders (unless delegation is used).

thanks

**Pull request merged**
